robot_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: 
    - Joint_1
    - Joint_2
    - Joint_3
    - Joint_4
    - Joint_5

    
#Controller to continuously publish joint states/positions
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50